/**
 * PRmate Action 번들링 스크립트
 *
 * scripts/review.mts 및 의존성 전체를 단일 dist/review.js로 번들링
 * → GitHub Action 실행 시 `npm ci` 불필요, 수초 단축
 */
import { build } from 'esbuild';
import { rmSync, existsSync } from 'fs';
import { resolve } from 'path';

const DIST_DIR = resolve(process.cwd(), 'dist');

// 기존 dist/ 초기화
if (existsSync(DIST_DIR)) {
  rmSync(DIST_DIR, { recursive: true });
}

console.log('▶ PRmate Action 번들링 시작...');

await build({
  entryPoints: ['scripts/review.mts'],
  outfile: 'dist/review.js',
  bundle: true,
  platform: 'node',
  target: 'node20',
  format: 'cjs',
  minify: false, // 디버깅 편의를 위해 유지
  sourcemap: true,
  external: [], // 전부 번들 (Action 실행 시 node_modules 불필요)
  banner: {
    js: '#!/usr/bin/env node\n// PRmate bundled GitHub Action\n// Do not edit this file — regenerate with `npm run build:action`',
  },
  legalComments: 'external', // third-party 라이선스는 별도 파일로
  logLevel: 'info',
});

console.log('✅ 빌드 완료: dist/review.js');
